# Site settings

title: Kronosapiens Labs
email: kronovet@gmail.com
description: A technology company
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kronosapiens.github.io" # the base hostname & protocol for your site
twitter_username: kronosapiens
github_username:  kronosapiens

# Build settings

drafts: True
future: True

disqus_short_name: kronosapiens
disqus_show_comment_count: true
